project:
  type: website

website:
  title: "Hack.Diversity Intranet Homepage"
  navbar: 
    left: 
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Fellow Dashboard
      - href: cohorts.qmd
        text: Cohort Data
      - href: partners.qmd
        text: Partners at a Glance

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true