project:
  type: website

website:
  title: "Fellow Dashboard"
  navbar: 
    left: 
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Dashboard

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true